services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
        - .:/app
        - /app/node_modules
    environment:
        - NODE_ENV=development
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - "8080:8080"